version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd tests-e2e && npm install && npm run test-testnet-specific
workflows:
    build-and-test:
      jobs:
        - build-and-test:
            environment:
              NIGHTWATCH_ENV: chrome
              TESTPATTERN: features/core/login.feature
