name: UI Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        tests: [
          "features/core/login.feature"
        ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - run: cd tests-e2e && npm install && npm run test-testnet-specific
        env:
         TESTPATTERN: ${{ matrix.tests }}
         NIGHTWATCH_ENV: "chrome"