name: UI Tests

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        tests: [
          {
            env: "chrome",
            pattern: "features/core/login.feature"
          }
        ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        env:
         TESTPATTERN: ${{ matrix.pattern }}
         NIGHTWATCH_ENV: ${{ matrix.env }}
      - run: npm install
      - run: npm run test-testnet-specific